# Generated by Django 5.1.1 on 2024-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_articulo_delete_myapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='Arte'),
        ),
    ]
