# Generated by Django 5.1.1 on 2024-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_agregar_delete_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar',
            name='fecha',
            field=models.DateField(),
        ),
    ]
