# Generated by Django 5.1.1 on 2024-09-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_agregar_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
