# Generated by Django 5.1.1 on 2024-10-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_imagen_remove_agregar_imagen_agregar_imagena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregar',
            name='imagenA',
        ),
    ]
