# Generated by Django 5.1.2 on 2024-10-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_agregar_codigo_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregar',
            name='ubicacion',
            field=models.IntegerField(choices=[(0, 'Salón Gabriela Mistral'), (1, 'Hemeroteca'), (2, 'Sala Medina')], null=True),
        ),
    ]
