# Generated by Django 5.1.2 on 2024-10-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_agregar_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar',
            name='ubicacion',
            field=models.IntegerField(choices=[(0, 'Salón Gabriela Mistral'), (1, 'Hemeroteca'), (2, 'Salón Medina'), (3, 'Sala Ercilla'), (4, 'Salón Camilo Henríquez'), (5, 'Sector Alameda 1er piso'), (6, 'Sector Alameda 2do piso'), (7, 'Sector Moneda 1er piso'), (8, 'Sector Moneda 2do piso')], null=True),
        ),
    ]
