# Generated by Django 5.1.2 on 2024-10-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_agregar_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregar',
            name='codigo_qr',
        ),
    ]
