# Generated by Django 5.1.2 on 2024-10-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_agregar_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elemento',
        ),
    ]
