# Generated by Django 5.1.2 on 2024-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_agregar_codigo_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='agregar',
            name='pieza',
            field=models.IntegerField(choices=[(0, 'Busto'), (2, 'Pintura'), (3, 'Retrato'), (4, 'Otro')], null=True),
        ),
    ]
