# Generated by Django 5.1.2 on 2024-10-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_agregar_fecha_alter_agregar_pieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar',
            name='codigo_qr',
            field=models.ImageField(null=True, upload_to='qr_codes/'),
        ),
    ]
