# Generated by Django 5.1.1 on 2024-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_articulo_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
