# Generated by Django 5.1.1 on 2024-10-02 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_agregar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.RemoveField(
            model_name='agregar',
            name='imagen',
        ),
        migrations.AddField(
            model_name='agregar',
            name='imagenA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.imagen'),
        ),
    ]
