# Generated by Django 5.1.1 on 2024-10-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_agregar_imagena'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
        migrations.AddField(
            model_name='agregar',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
