# Generated by Django 5.1.1 on 2024-10-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_imagen_agregar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregar',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='static/imagenes'),
        ),
    ]
